City-of-Helsinki/drupal-helfi-platform

- composer.json
To test:
1. make new
2. Make sure that the hdbt_admin theme is also added to public/themes/custom
> UHF-8: UHF-8 Add hdbt_admin theme

- tools/make/project/install.mk
How to test:
- Install platform via oneliner (see readme for instructions)
- Run `make new`
- Check that base configurations gets installed
> UHF-X Base configuration makefile

- README.md
Read the README and make sure it makes sense.
Check also these PRs:
https://github.com/City-of-Helsinki/drupal-hdbt/pull/53
> UHF-923 Add documentation regarding the paragraph inception issue

- tools/make/project/install.mk
- wodby.yml
How to test:
- Check instructions from https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/69
- When the one above is approved, you may approve this one as well
> UHF-1023 Translations

- composer.json
How to test on platform:
- `composer create-project City-of-Helsinki/drupal-helfi-platform:dev-UHF-242_Linkedevents hel-platform --no-interaction --repository https://repository.drupal.hel.ninja/`
- Run `make new`
- Enable module helfi_linkedevents
- In the container, run `MIGRATE_LIMIT=10 drush migrate:import linkedevents_event`
- After completion, run `drush migrate:import linkedevents_offer`
- Go to *<site>/admin/content/linkedevents-event* and see that migrated events exist
- See that translations exist and have varying content
- Go to *<site>/admin/structure/linkedevents_event/settings/form-display* and add fields to entity form
- See that text fields and offer field are populated (if there is content in the source data)
- Note that there is no UI for offer field data, only the id is …
> UHF-242: Linked Events integration

- tools/make/project/install.mk
Let's try a different approach on translations.
How to test:
- Check instructions from https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/77
- When the one above is approved, you may approve this one as well
> UHF-1336 Translations

- .gitignore
> Allow hdbt -prefix theme names.

- public/themes/custom/hdbt_subtheme/templates/misc/icon.twig
Check the changed [icon.twig ](https://github.com/City-of-Helsinki/drupal-helfi-platform/pull/31/files)
> UHF-796 Lighthouse

- tools/make/project/install.mk
Added extra cache rebuild to install.mk.
> UHF-X Extra CR

- composer.json
- public/sites/default/settings.php
Siteimprove configuration values (API keys) fetched from environment variables.
> UHF-1172: Siteimprove

- CHANGELOG.md
- composer.json
- tools/make/project/install.mk
> UHF-2093 update helper

- docker/openshift/crons/migrate-tpr.sh
Reverts City-of-Helsinki/drupal-helfi-platform#60
> Revert "UHF-4551: Force update TPR service, errand service and service channe…"

- public/themes/custom/hdbt_subtheme/hdbt_subtheme.info.yml
- tools/make/project/install.mk
* Updated regions in HDBT Subtheme to match HDBT theme regions.
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/292
* https://github.com/City-of-Helsinki/drupal-helfi-sote/pull/366
* https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/148
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/315
* https://github.com/City-of-Helsinki/drupal-module-helfi-tpr/pull/118
> UHF-2976: Clean regions

- tools/make/project/install.mk
* [Fixed drush calls on locale updates](https://github.com/City-of-Helsinki/drupal-helfi-platform/commit/4fb0ccb72a6760f68a7308a7c564449f36a6ab1a)
* `git checkout UHF-7008_localization`
* `make fresh`
* Link to other PR
> UHF-7008 Localization

- public/themes/custom/hdbt_subtheme/package-lock.json
- public/themes/custom/hdbt_subtheme/package.json
* Updates the browserslist to match with hdbt.
* `git checkout UHF-4470_browserslist_update`
* `make drush-cr`
* https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/233
* https://github.com/City-of-Helsinki/drupal-helfi-kymp/pull/544
* https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/273
* https://github.com/City-of-Helsinki/drupal-helfi-sote/pull/479
* https://github.com/City-of-Helsinki/drupal-helfi-rekry/pull/134
* https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/187
* https://github.com/City-of-Helsinki/drupal-helfi-platform/pull/98
> UHF-4470: Changed browserslist to match with hdbt

- README.md
* Updated the README file with new contact email.
[UHF-8133]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update README.md with new contact email

- docker/openshift/entrypoints/20-deploy.sh
- public/sites/default/settings.php
* https://github.com/City-of-Helsinki/drupal-module-helfi-api-base/pull/94
[UHF-6316]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-6316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-6316: Deploy hooks, API account mapping

- public/themes/custom/hdbt_subtheme/hdbt_subtheme.info.yml
- public/themes/custom/hdbt_subtheme/hdbt_subtheme.libraries.yml
- public/themes/custom/hdbt_subtheme/package-lock.json
- public/themes/custom/hdbt_subtheme/package.json
* Added preinstall for package.json that checks if there is updates for browserslist db
* `git checkout UHF-7006_browserslist_db_automatic_update`
* Go under the hdbt_subtheme theme and run `nvm use && npm i && npm run build`
* You might need to comment the imports from _hdbt.scss file to make the build pass.
* The theme compiling should now say at some point:
```
> hdbt_subtheme@1.0.0 preinstall
> npx browserslist@latest --update-db
```
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/659
* https://github.com/City-of-Helsinki/drupal-helfi-platform/pull/129
* https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/360
* https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/371
* …
> UHF-7006: Browserslist db automatic update

- docker-compose.yml
[UHF-8517]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-8517: Increase max_allowed_packet db setting

- docker/openshift/entrypoints/20-deploy.sh
- docker/openshift/notify.php
- documentation/openshift.md
- https://github.com/City-of-Helsinki/drupal-tools/pull/7
> UHF-4627: A notify script to send Slack messages in case deployment fails

- public/themes/custom/hdbt_subtheme/README.md
* Documentation was updated to include more information.
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/684
* https://github.com/City-of-Helsinki/drupal-hdbt-admin/pull/221
* https://github.com/City-of-Helsinki/drupal-helfi-platform/pull/135
[UHF-4905]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-4905?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-4905 hdbt documentation

- docker/openshift/crons/base.sh
- docker/openshift/crons/migrate-hearings.sh
> remove hearing cron

- composer.json
- public/sites/default/settings.php
* Allow test to run on Drupal 10.
* Remove deprecated code.
* N/A.
* [Link to other PR](https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/617)
[UHF-9113]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9113?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-9113: Drupal 10 support

- .github/workflows/update-config.yml.dist
Reverts City-of-Helsinki/drupal-helfi-platform#229
> Revert "UHF-9913: Allow workflow files to be updated"

- .gitignore
- .gitignore.dist
* I would like to ignore `local.services.yml` file so that I don't accidentally commit it with my development settings. This file is included in automatic updates so updating it here should update it in all projects.
> Add local.services.yml to gitignore

- .github/workflows/test.yml.dist
- phpunit.platform.xml
- phpunit.xml.dist
* https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/578
* https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/576
> UHF-X: Upload browsertest output to test artifact

- .github/workflows/test.yml.dist
- phpcs.xml.dist
Also: https://github.com/City-of-Helsinki/drupal-tools/pull/29
> Add Generic.PHP.RequireStrictTypes sniff

- docker/openshift/entrypoints/20-deploy.sh
- Switch to production image on your instance: https://github.com/City-of-Helsinki/drupal-docker-images/tree/main/openshift/drupal#testing-production-image-locally
- Add following changes to docker-compose.yml:
```diff
--- a/compose.yaml
+++ b/compose.yaml
@@ -4,10 +4,11 @@ services:
image: "${DRUPAL_IMAGE}"
hostname: "${COMPOSE_PROJECT_NAME}"
volumes:
-      - .:/app:delegated
+      - .:/var/www/html:delegated
depends_on:
- db
environment:
+      SKIP_DEPLOY_SCRIPTS: "true"
STAGE_FILE_PROXY_ORIGIN: "${STAGE_FILE_PROXY_ORIGIN}"
STAGE_FILE_PROXY_ORIGIN_DIR: "${STAGE_FILE_PROXY_ORIGIN_DIR}"
APP_ENV: "${APP_ENV:-local}"
```
- Run make up shell and
```
cp /var/www/html/docker/openshift/entrypoints/20-deploy.sh /entrypoints/
cp /var/www/html/docker/openshift/init.sh /
```
- Run `make stop && …
> UHF-9939: Bring features from grants project to platform repo

- CHANGELOG.md
- composer.json
* Removed conflict rule for Drupal 10.3.
❗ Remind @khalima to revert the https://github.com/City-of-Helsinki/drupal-helfi-platform/pull/252/commits/26aa8f52bb802e5b09824b9239c6cb69ab267100 commit before merging to `main` ❗ 
* `composer create-project City-of-Helsinki/drupal-helfi-platform:dev-UHF-9493 yoursite --no-interaction --repository https://repository.drupal.hel.ninja/`
* Run `make new`
* https://github.com/City-of-Helsinki/drupal-helfi-platform/pull/252
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/780
* https://github.com/City-of-Helsinki/drupal-module-helfi-proxy/pull/73
* https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/653
[UHF-9493]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …
> UHF-9493: Drupal 10.3 compatibility

- public/sites/default/settings.php
* This thing was fixed
* Add `$settings['helfi_api_base.log_level'] = getenv('LOG_LEVEL') ?: (getenv('APP_ENV') === 'production' ? 'info' : 'debug');` to your settings.php.
* https://github.com/City-of-Helsinki/drupal-module-helfi-api-base/pull/180
[UHF-10751]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10751?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10751: Add log level variable

- docker/openshift/crons/pubsub.sh
* https://github.com/City-of-Helsinki/drupal-helfi-platform/pull/272
[UHF-10413]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10413?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10413: Check if pubsub is enabled

- public/sites/default/settings.php
* https://github.com/City-of-Helsinki/drupal-helfi-kymp/pull/986
[UHF-10549]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-10549: Move elasticsearch settings to settings.php

- docker/elastic-proxy/nginx.conf
[UHF-11581]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11581?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> UHF-11581: Log nginx errors to /dev/stderr

- public/sites/default/azure.settings.php
Adds cert verification to SQL connection.
https://github.com/City-of-Helsinki/drupal-docker-images/pull/60
> Enable DB cert verification
