tools/make/project/install.mk
Switched to `drush-deploy`. With this command on every drupal instance we can at least try to update configurations with hook_deploy_NAME.
=> UHF-X post install

composer.json
Running `composer create-project ...` on composer 2.1 produces
Temporarily removed the "git commit hook file" copy procedure from post update cmd.
=> UHF-X Composer v2.1

public/themes/custom/hdbt_subtheme/README.md, public/themes/custom/hdbt_subtheme/hdbt_subtheme.info.yml, public/themes/custom/hdbt_subtheme/translations/fi.po, public/themes/custom/hdbt_subtheme/translations/sv.po
Check that the code looks good - This adds support for translations to the hdbt_subtheme strings in templates.
=> UHF-X: Add translation folders for hdbt_subtheme

drush/drush.yml
* Set default site-mail and account-mail to drupal@hel.fi
* ```composer create-project City-of-Helsinki/drupal-helfi-platform:dev-UHF-5426_email_update hel-platform --no-interaction --repository https://repository.drupal.hel.ninja/```
* Run `make new`
* Log in and go to https://hel-platform.docker.so/fi/user/1/edit and https://hel-platform.docker.so/fi/admin/config/system/site-information
* Check that the email is `drupal@hel.fi`
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/338
=> UHF-5426 Email update

CHANGELOG.md, composer.json
To test this:
- `composer create-project City-of-Helsinki/drupal-helfi-platform:dev-UHF-7959 drupal --no-interaction --repository https://repository.drupal.hel.ninja`
- `cd drupal`
- Make sure guzzle version 7+ is installed: `composer show "guzzlehttp/*"`
=> UHF-7959: Allow guzzle 7 to be installed

public/themes/custom/hdbt_subtheme/webpack.config.js
* Stopped the TerserPlugin from minifying the variable names Drupal and drupalSettings.
* https://github.com/City-of-Helsinki/drupal-hdbt/pull/668
* https://github.com/City-of-Helsinki/drupal-helfi-platform/pull/132
* https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/371
* https://github.com/City-of-Helsinki/drupal-helfi-asuminen/pull/248
* https://github.com/City-of-Helsinki/drupal-helfi-tyo-yrittaminen/pull/241
* https://github.com/City-of-Helsinki/drupal-helfi-kasvatus-koulutus/pull/380
* https://github.com/City-of-Helsinki/drupal-helfi-kuva/pull/174
* https://github.com/City-of-Helsinki/drupal-helfi-kymp/pull/643
* https://github.com/City-of-Helsinki/drupal-helfi-rekry/pull/262
* https://github.com/City-of-Helsinki/drupal-helfi-sote/pull/585
* …
=> UHF-8520 JS translation fix 

public/sites/default/settings.php
For projects using newrelic, garbage collector is called by newrelic extension which adds extra time.
The usual recommendation is to not have garbage collector called during a request, as it adds lot of time to the request, but for migration drush commands for example, garbage collector is needed.
Initially we've got gc disabled trough the base image, now switching to this approach
For non cli requests, do  ini_set('zend.enable_gc', 'Off');
* `git checkout PLATTA-4794`
* `make fresh`
* Run `make drush-cr`
- php --info | grep enable_gc  - should be On
- going to  /admin/reports/status/php should say zend.enable_gc=Off
[PLATTA-4794]: https://helsinkisolutionoffice.atlassian.net/browse/PLATTA-4794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjV …
=> PLATTA-4794 - disable garbage collector for non cli requests

tests/dtt/src/ExistingSite/ModuleEnabledTest.php
Issue: https://helsinkisolutionoffice.atlassian.net/browse/PLATTA-4943
Added dtt test to check if a module is enabled. At this point only dblog, if it is enabled the test will fail.
=> PLATTA-4943: Added test for checking if a module exists

docker/openshift/crons/base.sh, docker/openshift/crons/migrate-hearings.sh
Added cron for hearings
- [Setup the original PR](https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/554)
- Copy the migrate-hearings.sh to docker/openshift/crons folder
run `bash /app/docker/openshift/crons/migrate-hearings.sh`
migrations should run.
[UHF-8441]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-8441?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> hearing cron

CHANGELOG.md
Updated CHANGELOG.md with the base.sh change which prevents running cron during deployment
=> Updated CHANGELOG.md with the base.sh change which prevents running cron during deployment

tools/commit-msg
This fixes a minor annoyance in my workflow. The current git hook messes up fixup commits, so `git rebase --autosquash` does not work.
See: https://git-scm.com/docs/git-rebase#Documentation/git-rebase.txt---autosquash
=> UHF-X: allow fixup commits

composer.json
* Do not use Drupal 10.2 until [the issues with it](https://helsinkisolutionoffice.atlassian.net/browse/UHF-9488) have been fixed.
=> Conflict on D10.2 for now.

composer.json
* Removed version constraints for Drupal 10.2.0
[UHF-9488]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-9488 Drupal 10.2

docker-compose.yml
Alpine or Docker (not sure which) seems to fallback all non-existent domains (like `app`, `elastic`) to `127.0.0.1` if hostname is set to `xxxx.docker.so`.
For example:
=> UHF-9656: Use COMPOSE_PROJECT_NAME as hostname

composer.json, docker/openshift/crons/base.sh, docker/openshift/crons/linked-events.sh
- Add `docker/openshift/crons/linked-events.sh`.
* https://github.com/City-of-Helsinki/drupal-helfi-platform-config/pull/710
* https://github.com/City-of-Helsinki/drupal-tools/pull/26
[UHF-9576]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9576?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-9576: Add cron job for linked events migration

docker/openshift/entrypoints/10-preflight.sh
* Preflight script does not check exit code correctly.
* Switch to production image on your instance: https://github.com/City-of-Helsinki/drupal-docker-images/tree/main/openshift/drupal#testing-production-image-locally
* Add following changes to docker-compose.yml:
```diff
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -6,10 +6,13 @@ services:
image: "${DRUPAL_IMAGE}"
hostname: "${COMPOSE_PROJECT_NAME}"
volumes:
-      - .:/app:delegated
+      - .:/var/www/html:delegated
depends_on:
- db
environment:
+      OPENSHIFT_BUILD_NAME: "123"
+      SENTRY_DSN: '123'
+      SENTRY_ENVIRONMENT: '123'
STAGE_FILE_PROXY_ORIGIN: "${STAGE_FILE_PROXY_ORIGIN}"
STAGE_FILE_PROXY_ORIGIN_DIR: "${STAGE_FILE_PROXY_ORIGIN_DIR}"
APP_ENV: "${APP_ENV:-local}"
```
* Run `make up shell` and
* `cp …
=> Fix preflight script

compose.yaml
- Copy compose.yaml to your project
- Run `make stop up`
- Make sure `/fi/uutiset` endpoint does not complain about CORS headers
=> UHF-10127: Cors headers

docker/elastic-proxy/elastic.conf
Allows comma separated index names in elastic nginx proxy.
* https://github.com/City-of-Helsinki/helsinki-paatokset/pull/425
* Other related PRs listed in HDBT repo: https://github.com/City-of-Helsinki/drupal-hdbt/pull/1007 
[UHF-10102]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-10102: Allow comma separated index names in proxy URLs

compose.yaml
* Should allow running two separate elastic proxy instances at once.
[UHF-10102]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10102?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-10102: Add project name to elastic proxy traefik config

composer.json
* Lock version until patches are fixed.
[UHF-9493]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-9493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-9493: Lock Drupal version

documentation/openshift.md
* Update documentation
[UHF-10354]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10354?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
* https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/728
=> UHF-10354: Update documentation

tools/make/project/install.mk
If drush update commands are needed with drush locale update command, make fresh command fails.
Make fresh fails if update hooks are needed in locale update. Also there's no reason to first update translations and after run other commands.
* Drush deploy is run first.
* `git checkout run-drush-deploy-1st`
* `make fresh`
* Run `make drush-cr`
=> Run drush-deploy before local-update

composer.json
This fixes phpstan errors:
```
------ ---------------------------------------------------------------------- 
Line   src/Drush/Commands/PubSubCommands.php                                 
------ ---------------------------------------------------------------------- 
51     Call to method writeln() on an unknown class Drush\Style\DrushStyle.  
💡 Learn more at https://phpstan.org/user-guide/discovering-symbols   
57     Call to method writeln() on an unknown class Drush\Style\DrushStyle.  
💡 Learn more at https://phpstan.org/user-guide/discovering-symbols   
60     Call to method writeln() on an unknown class Drush\Style\DrushStyle.  
💡 Learn more at https://phpstan.org/user-guide/discovering-symbols   
------ ---------------------------------------------------------------------- 
```
More …
=> Autoload Drush\\Style

tools/make/drupal.mk
* Fixed 'make new' command.
[UHF-11098]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11098?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11098: Fixed 'make new' command.

tools/make/git.mk
Git complains about non-executable hooks and it's never run:
> hint: The '.git/hooks/commit-msg' hook was ignored because it's not set as executable.
> hint: You can disable this warning with `git config advice.ignoredHook false`.
* Copy the changed `tools/make/git.mk` file to your project
=> Make sure commit-msg Git hook is executable

public/sites/default/settings.php
Adding a shared config override for etusivu elasticsearch, to allow writing to suggestions index from all core sites.
We probably can't test this in local? So let's confirm this works in testing environments by checking the server connection status in /en/admin/config/search/search-api/server/etusivu , and making sure the suggestions index in etusivu is updated according to content updates
- Also test this on etusivu
- Select 1-2 additional sites and enable `helfi_recommendations` for testing 
* https://github.com/City-of-Helsinki/drupal-helfi-etusivu/pull/917
[UHF-10647]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-10647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-10647: Config override for etusivu elasticsearch (for suggestions indexing)

compose.yaml
* Update local elasticsearch to 8.18.2
* `git checkout UHF-11942`
* `make fresh`
* Run `make drush-cr`
* Link to other PR
[UHF-11942]: https://helsinkisolutionoffice.atlassian.net/browse/UHF-11942?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> UHF-11942: Update local elasticsearch
